### ISSUE TITLE
3D website cannot be opened

### ISSUE THREAD

**Issue by longfeili5170** [Boroviak-Lab/SpatialModelling#3]
Hi!

I'm very interested in your marmoset 3D transcriptomes website, but I can't open it. Could you please fix it.

Thanks!

**Comment by cap76** [comment]
Hi @longfeili5170 sorry about that. Is it possible to clarify the issue - what happens when you go to http://131.111.33.80:3838/marmoset3D/

**Comment by longfeili5170** [comment]
The address in the article is http://131.111.33.80/marmoset3D/. It does not seem to be jumping to port 3838 properly now.

http://131.111.33.80:3838/marmoset3D/ works fine

Thanks!! @cap76
