### ISSUE TITLE
3d dataset missing files

### ISSUE THREAD

**Issue by queenie-yip** [Boroviak-Lab/SpatialModelling#4]
Hi All, 

Thanks for your work - looks like a really powerful dataset that I'd love to be able to explore further. 

I'm trying to explore the CS7 stage embryos (demoCS7.m), and upon downloading and interacting with MATLAB 3D render, it appears a number of files are missing.

Within the LoadShots.m file there is a reference to:
- './Data/SpatialData/X.csv',
- '/Data/SpatialData/IDs_and_locations.csv'
- './Data/SpatialData/210527_Proj_shots_CS7_CP.csv'

None of these files appear in the Drive references Data folder - no do the contents of the available .csv files seems to make sense to substitue.

Let me know if you can help me getting the relevant information.

Thanks,

**Comment by Boroviak-Lab** [comment]
Thanks for bringing this to my attention, these files should have been there. I am uploading them now (the X.csv file is big so I will add it as a link to a GoogleDrive file in the SpatialData/Data/readme.txt) they should be available to download soon. Let me know if you find anything else missing and I will add it.

**Comment by queenie-yip** [comment]
Thanks guys!

I am now able to make expression plots of a gene of interest in the CS7 stage embryo i.e.
<img width="1305" alt="Screenshot 2023-02-09 at 11 22 09" src="https://user-images.githubusercontent.com/92360885/217682125-3576b560-cfeb-40d1-8652-444d2d6e0327.png">

This will be very helpful for my project.

Note though that I've only used the CS7 stage files, and that there are a number of files still missing for the CS5/6 stages.

I can work through the files to see which specific files are needed to make such plots if you'd like. Otherwise thanks again for your help with this.


Best,

**Comment by Boroviak-Lab** [comment]
That's brilliant, I will add the missing CS5/CS6 data but if you do notice that I've missed something please let me know. Thanks for your help in making this more accessible for everyone :-)
